### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent

### ISSUE THREAD

**Issue by mnjadidi** [pusheco/pushe-android-studio-sample#61] opened 2022-02-16 18:55 UTC
hi, i receive this error on android 12: please help

E/Pushe: java.lang.IllegalArgumentException: packageName: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

**Comment by mr-sarsarabi** [comment] 2022-02-18 10:31
same here. this error causes a crash.
here is the complete error with stacktrace:

    E/Pushe: java.lang.IllegalArgumentException: com.marcoweb.cityclub: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
          Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent 
    being mutable, e.g. if it needs to be used with inline replies or bubbles.
          at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
          at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
          at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
          at co.pushe.plus.fcm.v.e.get(FcmModule_ProvidesGeofencePendingIntentFactory.java:49)
          at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
          at co.pushe.plus.fcm.w.d.get(FcmGeofenceManager_Factory.java:1)
          at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
          at co.pushe.plus.fcm.v.a.b(DaggerFcmComponent.java:1)
          at co.pushe.plus.fcm.FcmInitializer.preInitialize(PusheInit.kt:18)
          at co.pushe.plus.internal.PusheInitializer.preInitializeComponents(PusheInitializer.kt:77)
          at co.pushe.plus.internal.PusheInitializer.initialize(PusheInitializer.kt:2)
          at co.pushe.plus.utils.InitProvider.onCreate(InitProvider.kt:1)
          at android.content.ContentProvider.attachInfo(ContentProvider.java:2404)
          at android.content.ContentProvider.attachInfo(ContentProvider.java:2374)
          at android.app.ActivityThread.installProvider(ActivityThread.java:7431)
          at android.app.ActivityThread.installContentProviders(ActivityThread.java:6948)
          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719)
          at android.app.ActivityThread.access$1500(ActivityThread.java:256)
          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090)
          at android.os.Handler.dispatchMessage(Handler.java:106)
          at android.os.Looper.loopOnce(Looper.java:201)
          at android.os.Looper.loop(Looper.java:288)
          at android.app.ActivityThread.main(ActivityThread.java:7842)
          at java.lang.reflect.Method.invoke(Native Method)
          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by mahdi-malv** [comment] 2022-02-19 14:29
Hey

Thanks for reporting this.

I think `2.5.2` should resolve this.

**Comment by mnjadidi** [comment] 2022-02-19 15:40
> 

i tried with 2.5.2 but not resolve, same error,

**Comment by mahdi-malv** [comment] 2022-02-19 18:35
@mnjadidi Could you share the stacktrace?

**Comment by mnjadidi** [comment] 2022-02-20 06:39
> @mnjadidi Could you share the stacktrace?

    java.lang.IllegalArgumentException: net.app.ipin: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:273)
        at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:151)
        at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:171)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:102)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)

**Comment by mnjadidi** [comment] 2022-02-20 06:40
> @mnjadidi Could you share the stacktrace?

java.lang.IllegalArgumentException: net.app.ipin: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at com.google.firebase.messaging.FirebaseMessaging.send(com.google.firebase:firebase-messaging@@21.0.0:44)
        at co.pushe.plus.fcm.m.accept(FcmMessaging.kt:20)
        at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onSubscribe(CompletablePeek.java:67)
        at io.reactivex.internal.operators.observable.ObservableIgnoreElementsCompletable$IgnoreObservable.onSubscribe(ObservableIgnoreElementsCompletable.java:51)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onSubscribe(ObservableDoOnEach.java:73)
        at io.reactivex.internal.operators.observable.ObservableTake$TakeObserver.onSubscribe(ObservableTake.java:55)
        at io.reactivex.internal.observers.BasicFuseableObserver.onSubscribe(BasicFuseableObserver.java:66)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.onSubscribe(ObservableObserveOn.java:106)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn.subscribeActual(ObservableSubscribeOn.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableObserveOn.subscribeActual(ObservableObserveOn.java:45)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableFilter.subscribeActual(ObservableFilter.java:30)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableTake.subscribeActual(ObservableTake.java:30)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableIgnoreElementsCompletable.subscribeActual(ObservableIgnoreElementsCompletable.java:31)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:91)
        at co.pushe.plus.utils.rx.SafeSingleFromCallable.subscribeActual(SafeSingleFromCallable.java:22)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleFlatMapCompletable.subscribeActual(SingleFlatMapCompletable.java:44)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletableTimeout.subscribeActual(CompletableTimeout.java:53)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletableToSingle.subscribeActual(CompletableToSingle.java:38)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleResumeNext.subscribeActual(SingleResumeNext.java:39)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
W/Pushe:     at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.observable.ObservableFlatMapSingle$FlatMapSingleObserver.onNext(ObservableFlatMapSingle.java:113)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(ObservableDoOnEach.java:101)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at co.pushe.plus.m0.c$a.run(Schedulers.kt:3)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)

**Comment by mahdi-malv** [comment] 2022-02-20 08:59
Hmm

This is related to `firebase-messaging` please override it by updating and see if it works.
Stacktrace leads to `FcmMessageing.send` first which is fcm internal

**Comment by mr-sarsarabi** [comment] 2022-02-20 11:49
There is also a related error happening when I try to install my app on android 12 with the `hms` module included.

    Installation did not succeed.
    The application could not be installed: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED

    Installation failed due to: 'INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: 
    /data/app/vmdl1818224253.tmp/base.apk (at Binary XML file line #528): com.huawei.hms.support.api.push.PushMsgReceiver: 
    Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present'

**Comment by mahdi-malv** [comment] 2022-02-20 19:13
It seems both `fcm` and `hms` modules (which add `firebase-messaging` and `huawei-pushkit`) are adding incompatible libraries (which I can not reproduce completely. I wonder why?)

To resolve both you may need to update both dependencies (`pushkit` and `fcm`) to a higher one that include fixes for these issues.

I'll merge newer versions for future releases

Issue should remain open until then.

**Comment by mahdi-malv** [comment] 2022-02-20 19:15
Fcm: https://github.com/firebase/firebase-android-sdk/issues/3115

PushKit: https://stackoverflow.com/questions/68373122/when-will-push-kit-include-the-androidexported-attributes-required-for-android

Override the release versions by explicitly adding them as your own libraries.

**Comment by mahdi-malv** [comment] 2022-03-09 12:09
Update to this issue: `2.6.1-beta03` ships some updates to `pushkit`, `fcm` and `workmanager` which caused this, along with some other dependency updates. Therefore, issue must be resolved with this version.

**Comment by mahdi-malv** [comment] 2022-03-28 07:40
Fixed in `2.6.1`

**Closed by mahdi-malv** 2022-03-28 07:40 UTC
Labels: bug
